### ISSUE TITLE
How to get the logged user in the backend app?

### ISSUE THREAD

**Issue by deniswsrosa** [shuaicj/zuul-auth-example#2]
I am not sure how to get the user login in the backend app, any hints?

**Comment by shuaicj** [comment]
@deniswsrosa there are at least two approaches imo:
- in zuul gateway you can add a request header (let's say 'X-Username') after parsing the jwt token, and forward to the backend service. See branch [issue-2-forward-username](https://github.com/shuaicj/zuul-auth-example/tree/issue-2-forward-username) and commit [4ed8ee2](https://github.com/shuaicj/zuul-auth-example/commit/4ed8ee260561a53d7f65103b1cad569d615be8bc).
- do auth in backend service instead of in zuul gateway, let the microservice itself handle the security stuff of its own. See branch [issue-2-auth-at-backend](https://github.com/shuaicj/zuul-auth-example/tree/issue-2-auth-at-backend) and commit [23e7879](https://github.com/shuaicj/zuul-auth-example/commit/23e7879989acb4f9a986e1d401099a840f306058).
